### ISSUE TITLE
ISSUE #1000 !!!!

### ISSUE THREAD

**Issue by jmaslek** [GamestonkTerminal/GamestonkTerminal#1000]
Nothing of value.

Just great job everyone

**Comment by DidierRLopes** [comment]
![cat-launch](https://user-images.githubusercontent.com/25267873/143924990-90bae792-4b77-48c1-9aeb-acf88020c74d.gif)

![rocket](https://user-images.githubusercontent.com/25267873/143925089-ebed4094-da4d-4a42-ba38-bf3ef4594489.gif)
