### ISSUE TITLE
[Bug] Stocks > DD > Finviz News

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1006]
**Describe the bug**
The following function is `broken` and `unused` :
- module : `gamestonk_terminal.stocks.due_diligence.finviz_view`
- function : `news`

Since this `news` function is unused maybe :
- a command should be added in : `stocks > dd` ?
- or the `news` should be remove (along with the `get_news` function in the model) ?

**To Reproduce**
Here is the code to reproduce the issue :
```python
from gamestonk_terminal.stocks.due_diligence import finviz_model, finviz_view

finviz_view.news(ticker="TSLA", num=5)
```

**Screenshots**
Here is the error :
```bash
...gamestonk_terminal\stocks\due_diligence\finviz_view.py in news(ticker, num)
     45     d_finviz_news = finviz_model.get_news(ticker)
     46     i = 0
---> 47     for s_news_title, s_news_link in {*d_finviz_news}:
     48         print(f"-> {s_news_title}")
     49         print(f"{s_news_link}\n")

ValueError: too many values to unpack (expected 2)
```

**Desktop (please complete the following information):**

- OS: `windows`
- Python version : `3.8`

**Additional context**
One solution would be to replace this line :
```python
for s_news_title, s_news_link in {*d_finviz_news}:
```

By this line :
```python
for s_news_title, s_news_link, *_ in d_finviz_news:
```

**Comment by DidierRLopes** [comment]
Fixed!
