### ISSUE TITLE
[Bug] Stocks > FA > Alpha Vantage Model

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1014]
**Describe the bug**
The following function seems `broken` and `unused` :
- module : `gamestonk_terminal.stocks.fundamental_analysis.av_model`
- function : `clean_fundamentals_df`

Maybe we should remove this function.

**To Reproduce**
```python
from gamestonk_terminal.stocks.fundamental_analysis import av_model

df_fa = av_model.get_balance_sheet(ticker="TSLA", number=5, quarterly=False)
df= av_model.clean_fundamentals_df(df_fa=df_fa, num=5)
```

**Screenshots**
```
KeyError: "None of ['fiscalDateEnding'] are in the columns"
```

**Desktop (please complete the following information):**

- OS: `windows`
- Python version : `3.8`

**Comment by jmaslek** [comment]
Am I missing something or does that function (clean fundamentals df) not get used?  I have searched for it and pulled up no occurrences...

**Comment by jmaslek** [comment]
So I removed the function.  Should've done it when I refactored but oops
