### ISSUE TITLE
[Bug] End date on yf load

### ISSUE THREAD

**Issue by CameronBeebe** [GamestonkTerminal/GamestonkTerminal#1023]
Just noticed that one line needs to be replaced after my merge on Feature/price (#961).  Forgot to revert after test.

<img width="525" alt="Screen Shot 2021-12-05 at 3 23 19 PM" src="https://user-images.githubusercontent.com/39677739/144766339-0767da25-9c9b-4574-9486-465804122661.png">

That line should not be deleted, and should be replaced or it will cause bugs.  My apologies!

**Comment by jmaslek** [comment]
Good catch
