### ISSUE TITLE
stocks - Behavioural analysis - Error API [Bug]

### ISSUE THREAD

**Issue by TenzinJhopee** [GamestonkTerminal/GamestonkTerminal#1026]
**Describe the bug**
stocks - Behavioural anaylsis - i set up my api key in config files. but it showed error like Error - could not handle the request 

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
stocks - ba - social -- Error api 

**Screenshots**
<img width="314" alt="Screen Shot 2021-12-06 at 9 24 19 AM" src="https://user-images.githubusercontent.com/21319725/144812195-9ae97f24-c456-4a28-93ed-b3309eca3c29.png">

<img width="430" alt="Screen Shot 2021-12-06 at 9 26 34 AM" src="https://user-images.githubusercontent.com/21319725/144812680-8b5fc6dc-fe58-4a75-8198-1ee8a1e1dba2.png">

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by DidierRLopes** [comment]
We've raised this already with the SI guys. Waiting for instructions from their side https://github.com/sentimentinvestor/sentipy/issues/11

FYI @ZeevoX

**Comment by ZeevoX** [comment]
> We've raised this already with the SI guys. Waiting for instructions from their side https://github.com/sentimentinvestor/sentipy/issues/11
> 
> FYI @ZeevoX 

Hi there, 
I'm not working with the Sentiment team anymore unfortunately, and I don't have the time to investigate. If they are not replying on GitHub, perhaps it would be worth emailing hello@sentimentinvestor.com directly.
All the best,
Timothy

**Comment by DidierRLopes** [comment]
> > We've raised this already with the SI guys. Waiting for instructions from their side [sentimentinvestor/sentipy#11](https://github.com/sentimentinvestor/sentipy/issues/11)
> > FYI @ZeevoX
> 
> Hi there, I'm not working with the Sentiment team anymore unfortunately, and I don't have the time to investigate. If they are not replying on GitHub, perhaps it would be worth emailing [hello@sentimentinvestor.com](mailto:hello@sentimentinvestor.com) directly. All the best, Timothy

Hey,

Sorry to hear that! Thanks for letting us know Timothy

**Comment by DidierRLopes** [comment]
Closing this as the SI team has changed and so did the endpoints. We already added one of their previous commands, and will be working on the others in the near future!
