### ISSUE TITLE
prompt.toolkit module fails to load

### ISSUE THREAD

**Issue by 23errg** [GamestonkTerminal/GamestonkTerminal#1027]
Fresh Win2022 install and gst dependencies gets a warm welcome. 
![2021-12-06 (2)](https://user-images.githubusercontent.com/74156936/144838562-60f29888-0ef1-44f5-8110-9a1100871bd9.jpg)

**Comment by piiq** [comment]
Hey @23errg! Great to have you with us!
Did you run `poetry install` in your `gst` environment?

**Comment by piiq** [comment]
If you use a venv I would suggest you try the following after you activate your environment:

```
pip install poetry
poetry install
```

poetry will install the dependencies from a .lock file and prompt_toolkit is in there.

as a side note can you check that when you call python3 from the environment it actually calls the python executable that's inside the environment? In bash I would type `which python3`, but unfortunately I don't know how to do that in windows cmd, It might be a case that inside the env python interpreter is simply called `python` and when you trigger `python3` it calls the system python3 installation that has no deps installed?

**Comment by 23errg** [comment]
> If you use a venv I would suggest you try the following after you activate your environment:
> 
> ```
> pip install poetry
> poetry install
> ```
> 
> poetry will install the dependencies from a .lock file and prompt_toolkit is in there.
> 
> as a side note can you check that when you call python3 from the environment it actually calls the python executable that's inside the environment? In bash I would type `which python3`, but unfortunately I don't know how to do that in windows cmd, It might be a case that inside the env python interpreter is simply called `python` and when you trigger `python3` it calls the system python3 installation that has no deps installed?

pip install poetry returned no error but poetry install returned a bunch.

<details><summary>errors</summary>
<p>

 (gst) C:\Users\username\GamestonkTerminal>poetry install
The virtual environment found in C:\ProgramData\Anaconda3\envs\gst seems to be broken.
Recreating virtualenv gamestonkterminal-BcPCW8ib-py3.8 in C:\Users\username\AppData\Local\pypoetry\Cache\virtualenvs\gamestonkterminal-BcPCW8ib-py3.8
Installing dependencies from lock file

Package operations: 253 installs, 0 updates, 0 removals

  • Installing attrs (21.2.0)
  • Installing pyrsistent (0.18.0)
  • Installing pywin32 (302)
  • Installing six (1.16.0)
  • Installing traitlets (5.1.1)

  ValueError

  File \C:\Users\username\AppData\Local\pypoetry\Cache\artifacts\1a\aa\39\10d6d07084f186f8cf6963cb033440402ad5088bb94d712239170f2ef6\attrs-21.2.0-py2.py3-none-any.whl does not exist

  at C:\ProgramData\Anaconda3\envs\gst\lib\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│


  ValueError

  File \C:\Users\username\AppData\Local\pypoetry\Cache\artifacts\48\e6\04\8118155ae3ec3a16dd2a213bbf7a7d8a62c596b2e90f73a22c896269f1\six-1.16.0-py2.py3-none-any.whl does not exist

  at C:\ProgramData\Anaconda3\envs\gst\lib\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│


  ValueError

  File \C:\Users\username\AppData\Local\pypoetry\Cache\artifacts\52\f1\b8\162cf4287ffa9609de1b3639dbc7ccf2185da2dca8de31ceea4966320a\pyrsistent-0.18.0-cp38-cp38-win_amd64.whl does not exist

  at C:\ProgramData\Anaconda3\envs\gst\lib\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│


  ValueError

  File \C:\Users\username\AppData\Local\pypoetry\Cache\artifacts\2a\be\45\0373c530f1c4cd1af80f0a0367b1d195a510ac38985e4328295e0de7fe\pywin32-302-cp38-cp38-win_amd64.whl does not exist

  at C:\ProgramData\Anaconda3\envs\gst\lib\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│


  ValueError

  File \C:\Users\username\AppData\Local\pypoetry\Cache\artifacts\5a\b2\fe\46afb6102bca2dd670dd45aadb434937ff929571e6a86f833bfc4ba9a4\traitlets-5.1.1-py3-none-any.whl does not exist

  at C:\ProgramData\Anaconda3\envs\gst\lib\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│


(gst) C:\Users\username\GamestonkTerminal>
</p>
</details>

A quick look in the gst virtual environment with Anaconda navigator shows python 3.8.12

**Comment by 23errg** [comment]
I manged to get gst working, the issue was from vs2015_runtime. It didn't update as it should, running `conda install -c anaconda vs2015_runtime` fixed the issue.

**Comment by 23errg** [comment]
I manged to get gst working, the issue was from vs2015_runtime. It didn't update as it should, running conda install -c anaconda vs2015_runtime fixed the issue.

**Comment by piiq** [comment]
Great to hear that! Join our Discord to share your experience with the terminal
