### ISSUE TITLE
[FR] feeding the prediction models with .csv

### ISSUE THREAD

**Issue by 23errg** [GamestonkTerminal/GamestonkTerminal#1031]
Maybe a folder that where users can feed the models with downloaded stock.csv.

**Comment by DidierRLopes** [comment]
I will try to have a YouTube this week on how you can customize your own automatic due diligence / routines using our reports section.

**Comment by 23errg** [comment]
> I will try to have a YouTube this week on how you can customize your own automatic due diligence / routines using our reports section.

That would be perfect!

**Comment by DidierRLopes** [comment]
PR #1193 adresses this! You can now download your own personal data and use our quantitative analysis and prediction techniques modules.

![Screenshot 2022-01-20 at 13 34 28](https://user-images.githubusercontent.com/25267873/150348756-8817db64-ec8b-43d6-93cc-3e92387ace0c.png)

In the future we hope to be able to use this data seamlessly to compare with stocks/forex/crypto/wtv other data to extract useful insights from it.
