### ISSUE TITLE
[IMPROVE] Stocks > Helper

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1042]
**What's the feature that should be improved?**
These two functions seems unused :
 - gamestonk_terminal/stocks/stocks_helper.py::view
 - gamestonk_terminal/stocks/stocks_helper.py::plot_view_stock

Are they used for some purpose that I don't about ?

**Describe how you would like the feature improved**
Removing this functions if they are found to be unnecessary.

**Comment by jmaslek** [comment]
Not that I can think of.  We scratched them in favor of candle
