### ISSUE TITLE
[Bug] Stocks > IEX load

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1044]
**Describe the bug**
Can't load stocks with source `IEX`.

**To Reproduce**
```bash
(✨) (stocks)> load gme --source iex -s 2020-10-20 -e 2020-12-1
```

**Screenshots**
```
index 0 is out of bounds for axis 0 with size 0 

'NoneType' object has no attribute 'empty'
```

**Desktop (please complete the following information):**

- OS: windows
- Python version : 3.8

**Additional context**
The error seems to come from this file :
- gamestonk_terminal/stocks/stocks_helper.py

The data is received from `IEX`.

But this part seems to empty the DataFrame somehow :
```python
df_stock_candidate = df_stock_candidate[
    (df_stock_candidate.index >= start.strftime("%Y-%m-%d"))
    & (df_stock_candidate.index <= end.strftime("%Y-%m-%d"))
]
```

**Comment by Chavithra** [comment]
The request made to IEX seems to only get last 30 days data :
```python
client.chartDF(ticker)
```

So filtering by date should only work if it's within 30 days range.

**Comment by jmaslek** [comment]
I will fix that to specify start and end 👍
