### ISSUE TITLE
[Bug] Stocks > Discovery

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1052]
Here is a list of potential issues in this module :
- Module : `gamestonk_terminal.stocks.discovery`

1/ `cfg.API_KEY_QUANDL` is used in ` :
- Module : `gamestonk_terminal.stocks.discovery.nasdaq_model`
- Function : `get_retail_tickers`
- Suggestion : replace it with something like `--API_KEY_NASDAQ` ?

2/ `get_article_list` function seems to loop and never return :
- Module : `gamestonk_terminal.stocks.discovery.seeking_alpha_model`
- Function : `get_article_list`
- Code to runned :
```python
from datetime import datetime
from gamestonk_terminal.stocks.discovery import seeking_alpha_model

start_date = datetime.strptime("2020-12-10", "%Y-%m-%d")
seeking_alpha_model.get_article_list(start_date=start_date, num=2)
```

3/ `ratings_view` seems `broken` and `unused` :
- Module : `gamestonk_terminal.stocks.discovery.marketbeat_view`
- Function : `ratings_view`
- Code runned :
```python
from gamestonk_terminal.stocks.discovery import marketbeat_view

marketbeat_view.ratings_view(other_args=["--threshold=1"])
```
- Error generated :
```
ValueError: could not convert string to float: ''
```

4/ `"-ascend"` `argument` seems weird :
- Module : gamestonk_terminal.stocks.discovery.disc_controller
- Function : `call_arkord`
- Suggestion : replace it with  `"--ascend"` ?

**Comment by jmaslek** [comment]
Will look at the last two points tomorrow but regarding the first one:

Nasdaq data link recently acquired quandl (or rebranded or something) and if you look at their api documentation it still calls the quandl package for python and uses the same quandl key.

So until they switch some documentation stuff up the quandl name still makes sense...kinda

**Comment by jmaslek** [comment]
So the get_article_list website needs some human verification:

Im not sure if we should scrap or figure out the js needed to get past it.

Pushing fix for other comments 
<img width="931" alt="Screen Shot 2021-12-13 at 4 43 57 PM" src="https://user-images.githubusercontent.com/18151143/145893822-951e2d14-eb4a-4e53-890e-fa726ab905db.png">
