### ISSUE TITLE
I installed anaconda

### ISSUE THREAD

**Issue by himansh-u** [GamestonkTerminal/GamestonkTerminal#1077]
PS E:\programs\GamestonkTerminal> conda
conda : The term 'conda' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ conda
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (conda:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by piiq** [comment]
After you install anaconda you should get "Anaconda prompt" as a separate program in your start menu. Can you try using that one?

**Comment by colin99d** [comment]
@himansh-u did you end up getting the issue resolved?

**Comment by colin99d** [comment]
This issue is not related to the terminal. I am going to go ahead and close.
