### ISSUE TITLE
[Bug] Technical Analysis > Finviz

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1136]
**Describe the bug**
Looks like this module is unused :
- `gamestonk_terminal.stocks.technical_analysis.finviz_view`

**Comment by jmaslek** [comment]
Does look that way.  the only usage of the finviz_model there is in discordbot, but that function doesn't seem to run.

**Comment by DidierRLopes** [comment]
This module seems to work and be used. See below
![Screenshot 2022-01-20 at 13 30 41](https://user-images.githubusercontent.com/25267873/150348189-729013c4-a90b-46de-a0e9-5ff632ece84f.png)

![Screenshot 2022-01-20 at 13 31 39](https://user-images.githubusercontent.com/25267873/150348328-12357ecb-64e0-4dd6-b828-dbd46e46d206.png)

Closing this!
