### ISSUE TITLE
[Bug] Stocks > Options > History

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1138]
**Describe the bug**
Find two issues with this function :
- function : `call_hist`
- classs : `OptionsController`
- module : gamestonk_terminal.stocks.options.options_controller

**To Reproduce**

```python
from gamestonk_terminal.stocks.options import options_controller

controller = options_controller.OptionsController(ticker="PM")
controller.call_exp(["--date=2022-01-07"])
controller.call_hist([
    "100",
    "--chain=MOCK_CHAIN_ID",
    "--raw",
    "--source=ce",
    "--limit=2",
])
```

This will display :
```
No correct strike input
```

**Issue A**
The issue is that it display :
`No correct strike input`

Even when you provide a valid `strike`.

I think we just need to replace :
```
ns_parser.strike in self.chain.puts["strike"]
```
By :
```
ns_parser.strike in self.chain.puts["strike"].values
```

**Issue B**
Once the first issue seems to be fixed I have this second error message :

```
gamestonk_terminal\stocks\options\op_helpers.py in convert(orig, to)
     77     if to == "%":
     78         clean = orig.replace("%", "").replace("+", "")
---> 79         return float(clean) / 100
     80     if to == ",":
     81         clean = orig.replace(",", "")

ValueError: could not convert string to float: '1,100.000'
```

This seems to appear only when `strike = 100`.

**Comment by DidierRLopes** [comment]
I think you didn't have latest version when this was created, I had fixed it 2 hours prior to this issue :)

See #1135 ! I also fixed the tests accordingly
