### ISSUE TITLE
[Bug] All CoinGecko 'disc' functions appear to not work

### ISSUE THREAD

**Issue by derekslenk** [GamestonkTerminal/GamestonkTerminal#1149]
**Describe the bug**
Under the crypto -> disc -> CoinGecko category, not one option works
Example:
````
(gst) slenk@enterprise:~/GamestonkTerminal$ python terminal.py crypto / disc / cgtrending

Connection error. Couldn't connect to CoinGecko and scrape the data. Please visit CoinGecko site, and check if it's not under maintenance

Unable to retrieve data from CoinGecko.
````

Except the CoinGecko site and API appear to be working? This gives us a nice response from their API:
````
curl -X 'GET' \
  'https://api.coingecko.com/api/v3/ping' \
  -H 'accept: application/json'
{"gecko_says":"(V3) To the Moon!"}
````

**To Reproduce**
````
python terminal.py crypto / disc / cgtrending
````

**Screenshots**
n/a imo

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04 in WSL2, Windows 11 Pro (21H2, build 22000.xxx)
- Python version: Python 3.8.10 system, conda details below

**Additional context**
````
(gst) slenk@enterprise:~/GamestonkTerminal$ conda info

     active environment : gst
    active env location : /home/slenk/miniconda3/envs/gst
            shell level : 2
       user config file : /home/slenk/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=5.10.60.1=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/slenk/miniconda3  (writable)
      conda av data dir : /home/slenk/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/slenk/miniconda3/pkgs
                          /home/slenk/.conda/pkgs
       envs directories : /home/slenk/miniconda3/envs
                          /home/slenk/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/5.10.60.1-microsoft-standard-WSL2 ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
````

**Comment by jmaslek** [comment]
Hey!  We are aware that these cause some issues.  There is currently a discussion going on in #1119 where we may scrap them.

The issue is that those commands scrape tables on their site, they are not just api calls, so the behavior is not the same (and why the functions fail).

**Comment by derekslenk** [comment]
Checked out that branch - I agree with https://github.com/GamestonkTerminal/GamestonkTerminal/pull/1119#issuecomment-1006706626 that all the non-api calls need to be removed. The pages being scraped appear to just call their own API, anyways.

**Comment by derekslenk** [comment]
For example, /en/dex would be the API query:  'https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&category=decentralized-exchange&order=market_cap_desc' \
  -H 'accept: application/json'

**Comment by derekslenk** [comment]
I could help with API queries if you guys need. I don't know the whole load_data system very well so I am intimidated to try myself, and it seems it might already be being worked on @jmaslek

**Comment by jmaslek** [comment]
We are happy to have any contributions!  @jose-donato and @JakubPluta are doing the heavy lifting with the load data stuff (also intimidating to me haha).  If you wanna work on the other function calls, just let us know and we can leave those to be fixed (instead of just nixed).

You can also hit us up on discord if you have any questions

**Comment by jose-donato** [comment]
Yea, we are planning to replace all the scraping with the respective api endpoints (the ones that exist at least), and drop the ones that are not possible. Would be great to have your help 🙌  @derekslenk

**Comment by jose-donato** [comment]
#1156 addresses this
