### ISSUE TITLE
unable to “poetry install”

### ISSUE THREAD

**Issue by MacLeeee** [GamestonkTerminal/GamestonkTerminal#1172]
when inputs “pip install -r requirements.txt”

![image](https://user-images.githubusercontent.com/23634845/148900706-3478c49b-35b0-492c-bf3d-fdeab1dd998e.png)

**Comment by Chavithra** [comment]
Hello, is it possible to let us know which version of `pip` you have ?

You can use this command to know the version :
```bash
pip -v
```

**Comment by MacLeeee** [comment]
> Hello,
> 
> is it possible to let us know which version of `pip` you have ?
> 
> You can use this command to know the version :
> 
> ```shell
> pip --version
> ```

pip 21.2.4 
python 3.8

**Comment by piiq** [comment]
@MacLeeee Are you on an m1 mac?

**Comment by MacLeeee** [comment]
> @MacLeeee Are you on an m1 mac?

yes!

**Comment by piiq** [comment]
> > @MacLeeee Are you on an m1 mac?
> 
> yes!

For now you are on your own, although you are not alone. As soon as my new m1 arrives, I will be in the same boat lol.

One of the ideas i had is to delete the poetry.lock and run `poetry update` followed by `poetry install` thus forcing it to pull the new dependency tree. if the packages are available for the m1 they should be resolved

**Comment by colin99d** [comment]
@MacLeeee did you install conda? I have an M1 and Conda has made all my issues disappear. Feel free to check out this link: https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html.

**Comment by colin99d** [comment]
I am going to go ahead and close this issue. If you have any further questions we would love to help you on our discord: https://discord.gg/Up2QGbMKHY.
