### ISSUE TITLE
[Bug] CoinMarketCap typo in README - API Key Section

### ISSUE THREAD

**Issue by stevedoor** [GamestonkTerminal/GamestonkTerminal#1195]
**Describe the bug**
- Only need one key, and that should be `GT_API_CMC_KEY` rather than `GT_CMC_API_KEY`

- From `config_terminal.py`:
```python
# https://coinmarketcap.com/api/
API_CMC_KEY = os.getenv("GT_API_CMC_KEY") or "REPLACE_ME"
```

- from `coinmarketcap_model.py`:
```python
cmc = CoinMarketCapAPI(cfg.API_CMC_KEY)
```

**Comment by DidierRLopes** [comment]
The issue has been fixed! Thank you for reporting and fixing it @stevedoor 😄
