### ISSUE TITLE
[Bug] Docker install -- error thrown when accessing ETF menu

### ISSUE THREAD

**Issue by yellowcandle** [GamestonkTerminal/GamestonkTerminal#1219]
**Describe the bug**
Error appeared when user is accessing the ETF menu on docker installation

**To Reproduce**
1. pull and build docker image using ``` docker pull ghcr.io/gamestonkterminal/gst-poetry:latest ```
2. run docker image using ``` docker run -it --rm ghcr.io/gamestonkterminal/gst-poetry:latest ```
3. go to ETF menu page by typing ```etf```

Expected behaviour:
ETF menu page loads successifully.  

Actual behaviour:
error as follows
```
Traceback (most recent call last):
  File "terminal.py", line 338, in <module>
    terminal()
  File "terminal.py", line 304, in terminal
    process_input = t_controller.switch(an_input)
  File "terminal.py", line 131, in switch
    return getattr(
  File "terminal.py", line 208, in call_etf
    from gamestonk_terminal.etf import etf_controller
  File "/home/python/gamestonk_terminal/etf/etf_controller.py", line 11, in <module>
    from thepassiveinvestor import create_ETF_report
ModuleNotFoundError: No module named 'thepassiveinvestor'
```

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra] macOS 12.0.1
- Python version [e.g. 3.6.8] 3.8.8

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
Hey!  Docker was updated today so this should be fixed.  Let us know if not

**Comment by yellowcandle** [comment]
Issue fixed after pulling latest image, thanks!
