### ISSUE TITLE
[IMPROVE] Charts Menu

### ISSUE THREAD

**Issue by jigsawsecurity** [GamestonkTerminal/GamestonkTerminal#1231]
**What's the feature that should be improved?**
A description of what's the feature you want improved, and a bit of context (why is that).
The chart menu typically covers the right top corner of the chart rendering the charts not useable since the price is covered by the menu.

**Describe how you would like the feature improved**
A description of what the current feature is vs what it would be after your suggestion.
Charting

**Possibly describe the ideal way to improve this**
If you have thought about how you would do it, add it here.
If possible putting the chart menu on the upper left would make it so it doesn't cover the right side where price or action is usually depicted. 

**Additional information**
Add any other information or screenshots about the feature improvement.

**Comment by DidierRLopes** [comment]
Hey @jigsawsecurity, I don't really understand what you mean. Can you share a screenshot so I can see the issue in more detail?

**Comment by jigsawsecurity** [comment]
Sure here is an example. See how the menu covers the chart?
![error](https://user-images.githubusercontent.com/14302946/150574534-2218ad59-761b-4adb-bb40-d01a669fe035.png)

**Comment by DidierRLopes** [comment]
> Sure here is an example. See how the menu covers the chart?
> ![error](https://user-images.githubusercontent.com/14302946/150574534-2218ad59-761b-4adb-bb40-d01a669fe035.png)

Gotcha! We want to improve our general plotting in the terminal to make it more consistent and nicer. See #1228. @piiq let's try to use `loc=best` so we avoid this situation
