### ISSUE TITLE
[Bug] Fundamental Analysis > DCF

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1236]
**Describe the bug**

Looks like there is a `str` to `float` conversion issue here :
- module : `gamestonk_terminal.stocks.fundamental_analysis.dcf_view`
- class : `CreateExcelFA`
- function : `create_workbook`

**To Reproduce**

Here is the code to generate the error :
```python
from gamestonk_terminal.stocks.fundamental_analysis import dcf_view, dcf_static
excel = dcf_view.CreateExcelFA(ticker="AAPL", audit=False)
excel.create_workbook()
```

**Screenshots**

Here is the error :
`ValueError: could not convert string to float: '9.20%'`

**Comment by colin99d** [comment]
Looks like their weekly reformat the site is going well
