### ISSUE TITLE
[QUESTION] How do I set a custom flair?

### ISSUE THREAD

**Issue by CoconutMacaroon** [GamestonkTerminal/GamestonkTerminal#1244]
I see that there are a bunch of flairs available
https://github.com/GamestonkTerminal/GamestonkTerminal/blob/6f74dd641bb5fae53bd53c80b14ce9eaef2b78a8/gamestonk_terminal/helper_funcs.py#L725-L749
I'd like to be able to set the flair to a custom string, say, `( )` or really anything I want. Is there a way I can use a custom string as the flair? Ideally, I'd like to use an environment variable, but something like passing it as an argument to the `terminal.py` program would work too.

Thanks,
CoconutMacaroon

**Comment by colin99d** [comment]
I will work on this one.
