### ISSUE TITLE
[Bug] Economy > Fred : option issue

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1256]
**Describe the bug**
Looks like there is an issue with this funcion.
- module : `gamestonk_terminal.economy.fred.fred_controller`
- class : `FredController`
- function : `call_rmv`

The `--all` option for the command `rmv` doesn't seem to work.

**Comment by DidierRLopes** [comment]
#1317 will fix this

**Comment by DidierRLopes** [comment]
Fixed in #1317
