### ISSUE TITLE
[Bug] Stocks/DPS/Prom

### ISSUE THREAD

**Issue by colin99d** [GamestonkTerminal/GamestonkTerminal#1277]
**Describe the bug**
The command is not running.

**To Reproduce**
Go to stocks/dps/prom

**Screenshots**
<img width="1127" alt="Screen Shot 2022-01-27 at 8 26 10 PM" src="https://user-images.githubusercontent.com/72827203/151470867-74802b4f-bfd9-480a-b292-3a067af7429b.png">

**Desktop (please complete the following information):**

- OS: Mac Monterey
- Python 3.8.12

**Comment by DidierRLopes** [comment]
I didn't have any issue.
<img width="1639" alt="Screenshot 2022-02-05 at 18 21 22" src="https://user-images.githubusercontent.com/25267873/152654011-649fad90-48a5-48ad-a96d-8709c610cdc3.png">

Am assuming the error is with linear regression done by stats model based on your traceback, thus added a protection there.
<img width="591" alt="Screenshot 2022-02-05 at 18 24 50" src="https://user-images.githubusercontent.com/25267873/152654125-b5dafee2-5fe6-40b1-9c26-dad7d9013874.png">

**Comment by DidierRLopes** [comment]
Fixed in #1317
