### ISSUE TITLE
[Bug] Alphavantage daily adjusted endpoint is now premium

### ISSUE THREAD

**Issue by jmaslek** [GamestonkTerminal/GamestonkTerminal#1283]
**Describe the bug**
Alphavantage daily adjusted endpoint is now premium so the `load {} --source av` throws error

**To Reproduce**
`python terminal.py stocks/load aapl --source av`

**Comment by DidierRLopes** [comment]
<img width="1343" alt="Screenshot 2022-02-05 at 18 16 15" src="https://user-images.githubusercontent.com/25267873/152653859-00b10d0a-da2c-4a12-9470-002a3d34d434.png">

This is being flagged correctly on the terminal. Is there anything in specific you want out of this?

**Comment by jmaslek** [comment]
is there any reason to keep it?

**Comment by DidierRLopes** [comment]
> is there any reason to keep it?

Is there any reason to remove it? I mean, if you have a Premium key it will work.

**Comment by jmaslek** [comment]
¯\_(ツ)_/¯. we have historically gotten rid of premium stuff

**Comment by DidierRLopes** [comment]
Let's leave it for now! Closing this because it's not really a bug 😋
