### ISSUE TITLE
[Bug] Cryptocurrency > Discovery > Dappradar

### ISSUE THREAD

**Issue by Chavithra** [GamestonkTerminal/GamestonkTerminal#1287]
**Describe the bug**
Error from these functions :
- `get_top_dexes`
- `get_top_games` 
- `get_top_dapps`

These functions are from the module :
- `gamestonk_terminal.cryptocurrency.discovery.dappradar_model`

The error :
- {"error":"Bad request"}

**Comment by jose-donato** [comment]
aff, they must have changed the api. will take a look

**Comment by jose-donato** [comment]
@Chavithra can you confirm that you still get this error?
i'm not getting this on my end

**Comment by Chavithra** [comment]
You are right it works now !

Maybe it was some midnight maintenance on these 3 endpoints.
