### ISSUE TITLE
[Bug] Finnhub's past and future IPOs functions return nothing

### ISSUE THREAD

**Issue by JerBouma** [GamestonkTerminal/GamestonkTerminal#1301]
**Describe the bug**
There is no data available anymore for past and future IPOs from Finnhub.

**To Reproduce**
When you access stocks/disc and use _pipo_ or _fipo_ you get no data.

**Screenshots**
![image](https://user-images.githubusercontent.com/46355364/152156882-b307814d-a512-4d67-997c-e5a96d31b19f.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Python version 3.8

**Comment by jmaslek** [comment]
Is your API key defined?
<img width="1164" alt="Screen Shot 2022-02-03 at 4 12 36 PM" src="https://user-images.githubusercontent.com/18151143/152429751-2b4377a0-d227-433a-bf8b-259a04d7aba5.png">

**Comment by JerBouma** [comment]
Ahh, then this item fits with #1307. It is (to me) unclear which items require an API key and which don't. Yes, I could open the config file but that shouldn't be mandatory right.
