### ISSUE TITLE
[IMPROVE]Forex titles do not follow convention

### ISSUE THREAD

**Issue by colin99d** [GamestonkTerminal/GamestonkTerminal#1322]
**What's the feature that should be improved?**
 USD/GBP should have a title of USD/GBP and not GBP/USD on forex/candle.

**Describe how you would like the feature improved**
Fix the title.

**Comment by colin99d** [comment]
This looks like it is now match a google search of USD/GBP.

**Comment by jmaslek** [comment]
You behind. I fixed when I saw the article ;)
