### ISSUE TITLE
[Bug] Make a report in Jupyter menu

### ISSUE THREAD

**Issue by jantaf** [GamestonkTerminal/GamestonkTerminal#1332]
**Describe the bug**
When I want to make a report from the jupyter menu, I got an error in all options that appear in this menu. 

**To Reproduce**

1. Init GamestonkTerminal
2. Select /jupyter/reports
3. Choose any one option in this menu(econ_data, due_diligence, etc.)
4. Show the error(See the screenshot in the next section)

**Screenshots**
![image](https://user-images.githubusercontent.com/1208494/152969129-21d93c18-4e40-4851-8003-cca1108671b0.png)

**Desktop (please complete the following information):**

- OS: MacOS Monterrey
- Python version: 3.8.10

**Additional context**

I have investigated something and I see that the problem is in the file decorators.py in line 53
In this part of code:
` 
                formatted_arguments = ", ".join(
                    args_passed_in_function + kwargs_passed_in_function
                )`

**Comment by DidierRLopes** [comment]
Hey!

Thanks for reporting this!

I think that #1327 should have fixed this! Let me know if it works as expected 😄
