### ISSUE TITLE
setenv CMC api key does not work

### ISSUE THREAD

**Issue by Slamoth** [GamestonkTerminal/GamestonkTerminal#1340]
Even if I enter the CMC API key in the setenv file it does not work.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/6489169/153190807-2ed9f67a-51a7-4a1d-8cfb-0102766b9f2a.png">

But when I curl with the same API key to CMC it works.
command is : `curl -H "X-CMC_PRO_API_KEY: ************************" -H "Accept: application/json" -d "start=1&limit=5000&convert=USD" -G https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest`

```json
{"status":{"timestamp":"2022-02-09T11:23:55.074Z","error_code":0,"error_message":null,"elapsed":1,"credit_count":1,"notice":null},"data":[{"id":8105,"name":"8l3juac3stc","symbol":"k9hllal6wyo","slug":"tymech2501r","cmc_rank":3439,"num_market_pairs":2351,"circulating_supply":4751,"total_supply":4859,"max_supply":3417,"last_updated":"2022-02-09T11:23:55.074Z","date_added":"2022-02-09T11:23:55.074Z","tags":.....
```

**Comment by piiq** [comment]
If I understand correctly it's only the test failing, and the requests in cmc commands actually work
<img width="561" alt="image" src="https://user-images.githubusercontent.com/11668535/155023327-4e5b38dc-f179-46aa-beb6-0caf69501cc1.png">

**Comment by piiq** [comment]
@minhhoang1023 will this also be fixed by https://github.com/GamestonkTerminal/GamestonkTerminal/pull/1357?
