### ISSUE TITLE
 [Bug] Bigmac index does not work

### ISSUE THREAD

**Issue by JerBouma** [GamestonkTerminal/GamestonkTerminal#1365]
**Describe the bug**
It seems that it no longer returns any data, perhaps the API changed.

```
2022 Feb 15, 05:06 (✨) /economy/ $ bigmac -c USA,EUR,MEX,CAN,UAE,RUS

Unable to get big mac data

2022 Feb 15, 05:08 (✨) /economy/ $
```

**To Reproduce**
- Open economy
- Use bigmac with anything

**Desktop (please complete the following information):**
- OS: Windows 11
- Python version: 3.8

**Comment by JerBouma** [comment]
Which API is linked to this command? I see Nasdaq Data Link but it doesn't appear as an option under /keys?

**Comment by jmaslek** [comment]
It's quandl (should change this over since nasdaq finally changed)

**Comment by JerBouma** [comment]
Sounds about right!
