### ISSUE TITLE
[Bug] Efficient Frontier

### ISSUE THREAD

**Issue by DidierRLopes** [GamestonkTerminal/GamestonkTerminal#1370]
When loading `example.csv` on the portfolio menu, we get:
![Screenshot 2022-02-15 at 14 30 22](https://user-images.githubusercontent.com/25267873/154082489-cf71fba6-db78-40e6-a6da-c1533337796a.png)

**Comment by minhhoang1023** [comment]
@DidierRLopes how do you load the `example.csv` ? Dunno how to do that and don't see instructions with help

**Comment by DidierRLopes** [comment]
This is actually not related with the load but when you try to use `ef` or other without having no ticker selected
