### ISSUE TITLE
[Bug]Stock Screener - (applicable everywhere) Sorting labels have spaces; spaces are incompatible.

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#1420]
Choices for sorting in ownership have a space in them; the inputs fields are not able to handle a space.

2022 Feb 25, 17:29 (✨) /stocks/scr/ $ ownership -s Float Short
ownership: error: argument -s/--sort: invalid choice: 'Short' (choose from 'Ticker', 'Market Cap', 'Outstanding', 'Float', 'Insider Own', 'Insider Trans', 'Inst Own', 'Inst Trans', 'Float Short', 'Short Ratio', 'Avg Volume', 'Price', 'Change', 'Volume')

**Comment by piiq** [comment]
resolved by https://github.com/GamestonkTerminal/GamestonkTerminal/pull/1443
