### ISSUE TITLE
Create a text communication channel : public feed[FR]

### ISSUE THREAD

**Issue by divyank0** [GamestonkTerminal/GamestonkTerminal#143]
**What's the problem of not having this feature?**
GameStonk Terminal is great at analysis of stocks, But to share and receive Ideas, I would have to use reddit or some other channel. An inbuilt channel would provide instantaneous news, Ideas and will increase the usage of the product.  It will also have more focused audience. 

**Describe the solution you would like**
To start with,  a public channel to continuously stream text messages should suffice. 
User should be able to post to this channel, and receive messages.  
User authentication, validation etc. can be put up in later versions. 

hence Proposing a new command
`terminal chat`
this will open up a new terminal which will continuously stream new messages till the terminal is closed

**Describe alternatives you've considered**
There is of course wsb discord channel.  But I believe there is a space for more savvy traders. 

**Additional information**
Obviously this is just a brainfart of mine, and not very fleshed out. I would like to test this idea here, to see if this is something that people would like. I believe Bloomberg terminal also has a similar feature.

**Comment by aia** [comment]
We added a Discord chat.
