### ISSUE TITLE
[Bug]Stock Screener - No Ticker Found with several commands

### ISSUE THREAD

**Issue by minhhoang1023** [GamestonkTerminal/GamestonkTerminal#1441]
**Describe the bug**
<img width="444" alt="image" src="https://user-images.githubusercontent.com/40023817/156991749-e8df269d-1f83-4ef2-b95b-dade4aea7e40.png">

this is due to finvizfinance package is outdated, and not able to scrape the website.

**To Reproduce**
finvizfinance version: 0.9.10

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Mac Sierra]
- Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by GabrieleRisso** [comment]
Im experiencing the same error, can l help to fix

**Comment by piiq** [comment]
resolved by https://github.com/GamestonkTerminal/GamestonkTerminal/pull/1443

**Comment by minhhoang1023** [comment]
@GabrieleRisso It's fixed now! Let me know if it still doesn't work for you

**Comment by GabrieleRisso** [comment]
@minhhoang1023 I've just updated the terminal and the error is not coming out as before. There is no output showing in the terminal

**Comment by minhhoang1023** [comment]
@GabrieleRisso can you share with me the command you used? Tested intensively and it worked for us
