### ISSUE TITLE
[FR] Crypto should load crypto using Yahoo finance

### ISSUE THREAD

**Issue by DidierRLopes** [GamestonkTerminal/GamestonkTerminal#1460]

**Comment by jose-donato** [comment]
u mean with `--source yf`?

**Comment by jmaslek** [comment]
ya.  and probably as the default?

**Comment by jose-donato** [comment]
> ya.  and probably as the default?

hm, i think coingecko/messari/coinpaprika/... are way better for this purpose. but i agree adding it as an additional source

**Comment by jmaslek** [comment]
> Is the reason being to be consistent with stocks?

Consistency/ no api key/ data returned is actually OHLVC
