### ISSUE TITLE
[Bug] Common bot functions using imgur/discord specific code

### ISSUE THREAD

**Issue by jose-donato** [GamestonkTerminal/GamestonkTerminal#1464]
**Describe the bug**
Some bot functions are uploading images to imgur while other functions are not. I think all the functions should not use imgur and just export the image location (like some functions are already doing) and then outside the function we can decide whether imgur is used or not to get a public URL for the image.

**This makes bots on other platforms to break if imgur is not configured** (some platforms do not need it and the images can be uploaded directly to the platform).

**To Reproduce**
Example of a function that uses imgur or other specific discord code (disnake): [dd_est](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/bots/stocks/due_diligence/est.py)

Example of a function that does not use it:
[ta_sma](https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/bots/stocks/technical_analysis/sma.py)

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
Not applicable

**Additional context**
@tehcoderer @colin99d are you aware of this already?

**Comment by northern-64bit** [comment]
> **Describe the bug** Some bot functions are uploading images to imgur while other functions are not. I think all the functions should not use imgur and just export the image location (like some functions are already doing) and then outside the function we can decide whether imgur is used or not to get a public URL for the image.

I agree with this. Imgur has an (free) api limit and thus it hinders large scale deployment of the bot so we should switch away from it.

The original solution with imgur was created by me since you had to upload images to discord with a public url and imgur was an easy way to create one. Now when there's another way of doing this one should definitely switch to it.

If I can help with the implemention of the direct image upload (replacing imgur), then I'd be happy to.

**Comment by jose-donato** [comment]
> > **Describe the bug** Some bot functions are uploading images to imgur while other functions are not. I think all the functions should not use imgur and just export the image location (like some functions are already doing) and then outside the function we can decide whether imgur is used or not to get a public URL for the image.
> 
> I agree with this. Imgur has an (free) api limit and thus it hinders large scale deployment of the bot so we should switch away from it.
> 
> The original solution with imgur was created by me since you had to upload images to discord with a public url and imgur was an easy way to create one. Now when there's another way of doing this one should definitely switch to it.
> 
> If I can help with the implemention of the direct image upload (replacing imgur), then I'd be happy to.

Yea, exactly! Imgur was a great idea and perfect to bootstrap the discord bot. Kudos for that 🙌 

But since the majority of the platforms allow to upload the images directly I would suggest that all the functions save the files locally by default and each platform controller reads the file and uploads to the platform (and removes the file once it is finished). If a platform does not allow this, we can just use the imgur in those situations (**but outside the common bot functions**)

**Comment by tehcoderer** [comment]
```
            if cfg.IMAGES_URL:
                image_link = cfg.IMG_DIR / imagefile
```

if you use this for the other bots you'll get the images location without uploading to imgur and can then use that to upload them. I'm working on making it a little more user friendly

![image](https://user-images.githubusercontent.com/61340027/157926542-e34fc77a-d100-44e2-8466-20078e2aaa8d.png)

**Comment by tehcoderer** [comment]
https://github.com/tehcoderer/GamestonkTerminal/commit/e605c1278365c5c9f076b0743e545f2ad701ce34#r68519151

Let me know haha
