### ISSUE TITLE
[Bug] Dashboards fails to launch.

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#1555]
/jupyter/dashboards - failure to launch.

I know I have Voila installed because I have been using it already, this problem is new. 

<img width="1142" alt="Screen Shot 2022-03-25 at 12 19 55 PM" src="https://user-images.githubusercontent.com/85772166/160187451-45576109-c975-4954-a31f-b3ed13e753f0.png">

Ran git pull & poetry install  just now. 
```
(gst) Danglewoods-MacBook-Pro:gamestonkterminal danglewood$ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), 507 bytes | 56.00 KiB/s, done.
From https://github.com/GamestonkTerminal/GamestonkTerminal
   d00b098b9..6ee2a001a  feat-add-yf-crypto -> origin/feat-add-yf-crypto
Already up to date.
(gst) Danglewoods-MacBook-Pro:gamestonkterminal danglewood$ poetry install
Installing dependencies from lock file

Package operations: 0 installs, 2 updates, 0 removals

  - Updating pytz (2021.3 -> 2022.1)
  - Updating grpcio (1.42.0 -> 1.45.0)

Installing the current project: GamestonkTerminal (0.1.0)
(gst) Danglewoods-MacBook-Pro:gamestonkterminal danglewood$ python terminal.py
```

**Comment by colin99d** [comment]
Looks like Voila [does not work with the newest version of Jinja](https://github.com/voila-dashboards/voila/pull/1127). The PR shown above is still failing tests, so it might be some time before it is merged. I think the best strategy for now is to force poetry to use a lower version of Jinja. However, we should keep this bug open so we remember to take out the forced lower version of Jinja later. Want thoughts from @DidierRLopes or @piiq before I do this though.

**Comment by piiq** [comment]
I've previously pinned jinga version to 3.0.3 to make it work. I'll address it again in the PyInstaller PR 'cause I will be touching dep files there

**Comment by DidierRLopes** [comment]
Sounds good to me!
