### ISSUE TITLE
[IMPROVE] Provide Architecture Diagram

### ISSUE THREAD

**Issue by zkniebel** [GamestonkTerminal/GamestonkTerminal#224]
**What's the feature that should be improved?**
Architecture documentation. For those wondering how it works and wanting to understand the project at a high-level before diving in head first, it would be helpful to have an architecture diagram (maybe some write-up too, but the diagram should be a sufficient start) to illustrate the functionality of the solution.

**Describe how you would like the feature improved**
Architecture diagram created to show involved system components and integrations.

**Possibly describe the ideal way to improve this**
Create architecture diagram. Potentially add some architecture write-ups in the future, but diagram should be sufficient for now.

**Additional information**
None.

**Comment by MLNW** [comment]
Good idea! I recommend this model: https://c4model.com/

**Comment by DidierRLopes** [comment]
I think https://github.com/GamestonkTerminal/GamestonkTerminal/blob/main/CONTRIBUTING.md addresses this. So will be closing this ticket. :)

Let me know if you think otherwise
