### ISSUE TITLE
[FR] non interactive mode

### ISSUE THREAD

**Issue by peter-clemenko** [GamestonkTerminal/GamestonkTerminal#382]
**What's the problem of not having this feature?**
Having a non interactive mode that lets you just run a command and dump to stdout would help with scripting using the terminal as a data source

**Describe the solution you would like**
Add a non interactive execution mode that just lets me one and done a command

**Describe alternatives you've considered**
A websocket server could also help, but might be overcomplicated for this.

**Comment by DidierRLopes** [comment]
Hey @peter-clemenko ,

Do you mean when a plot pops up? 

The `plt.ion()`?

**Comment by peter-clemenko** [comment]
Negative, I mean I want to be able to do a one liner and run it like a standard command like cat or ls.

**Comment by hinxx** [comment]
I guess OP is after executing several commands like in a script. Or chaining the commands like:
```
load gme; dd; ftd
```
I tried that myself the other day and it does not work. Maybe one could use `expect` to do this on Linux?

>  A websocket server could also help, but might be overcomplicated for this.

On Linux using local unix socket would be simpler, I guess. Upgrading that idea to using TCP socket might be something that would work for all OSes and even allow remote control of GST. The idea would be to accept input messages (commands) from user and delivering responses back.. like a simplified web server. Sending text replies would be straightforward, sending binary data, like images, might be a bit of an issue without a dedicated client.

**Comment by peter-clemenko** [comment]
> I guess OP is after executing several commands like in a script. Or chaining the commands like:
> 
> ```
> load gme; dd; ftd
> ```
> 
> I tried that myself the other day and it does not work. Maybe one could use `expect` to do this on Linux?
> 
> > A websocket server could also help, but might be overcomplicated for this.
> 
> On Linux using local unix socket would be simpler, I guess. Upgrading that idea to using TCP socket might be something that would work for all OSes and even allow remote control of GST. The idea would be to accept input messages (commands) from user and delivering responses back.. like a simplified web server. Sending text replies would be straightforward, sending binary data, like images, might be a bit of an issue without a dedicated client.

Damn straight. I'm less interested in the images and more interested in pulling raw data. I'll handle dataviz on my end, I just want to use this as a means to pull data in a centralized way.

**Comment by aia** [comment]
Take a look at the papermill menu and Jupyter notebook integration examples:
https://github.com/DidierRLopes/GamestonkTerminal/blob/main/notebooks/templates/due_diligence.ipynb

The terminal will run papermill for you, but you can run papermill yourself.

To accomplish what you are looking to do

1. Create a Jupyter notebook with logic that you want
2. Write data in the format that you like in your Jupyter notebook
3. Run Jupyter notebook with papermill

**Comment by peter-clemenko** [comment]
That's interesting, any chance gst can be put on pip?

**Comment by aia** [comment]
> That's interesting, any chance gst can be put on pip? I'm not using jupyter for this and pip would make it easier to spin up on my end for this inside docker.

We are working towards a pypi release.

Here's our roadmap - https://github.com/DidierRLopes/GamestonkTerminal/blob/main/ROADMAP.md.

We are finishing an MVC refactoring, publishing a docker container, adding several developer and backend features.

**Comment by DidierRLopes** [comment]
Hey @peter-clemenko, we are already on docker. So feel free to check it out.

I'm closing this ticket because our notebook reports, does this non-interactive mode concept
