### ISSUE TITLE
[Bug] The Modules do not work what so ever (READ FOR MORE)

### ISSUE THREAD

**Issue by swagrisegaming** [GamestonkTerminal/GamestonkTerminal#426]
**Describe the bug**
Ok so the yfinance not importing bug happened to me but I managed to "pip install yfinance" but now it's saying that "ModuleNotFoundError: No module named 'alpha_vantage'" when I pip install this one it keeps on going then it stops working

**To Reproduce**
I followed all your steps correctly, double-checked it and this problem happened again, Idk why the modules will not import, I've been spending 2 hours (I'm new to coding) trying to fix it, my pea brain hasn't figured out a solution so your help is appreciated DidierRLopes

Screenshots
![Capture](https://user-images.githubusercontent.com/33618635/116783211-cdf16180-aad0-11eb-98c2-3c49a85e9cf4.PNG)

Desktop (please complete the following information):
Ironically I'm using python 3.6.8 because the gamestonk terminal was coded in it so I wanted to replicate it but all the typing was done in the Anaconda prompt

Additional context
in practicality, all the imported modules are missing or non-existent according to the anaconda prompt (keep in mind I followed every step and retried like 3 times)
Nothing but thank you if you end up reading this

**Comment by DidierRLopes** [comment]
Hey @swagrisegaming can you join discord and message me personally? I can help you go through this?

**Comment by swagrisegaming** [comment]
Yes sure, whats your discord, I'll add it ASAP

**Comment by DidierRLopes** [comment]
Join the group discord which is on the README, and on the group my name is SexyYear

**Comment by aia** [comment]
Assuming this was resolved on Discord.
