### ISSUE TITLE
Prediction algorithms can return negative stock prices

### ISSUE THREAD

**Issue by Bainsbe** [GamestonkTerminal/GamestonkTerminal#45]
Issue outlined in the title, may be worth setting a bottom bound on the prices to default to 0 if prediction is <0 

![image](https://user-images.githubusercontent.com/55219220/109358226-6b21e680-7851-11eb-8920-13f5bf56ddcd.png)

**Comment by jamesphillipturpin** [comment]
I think the more natural solution is to fit to y=np.log(price) and then predict y. Return to the user price=np.exp(y). You could still get a price of 0.00 by rounding, say, 0.002 down to 0.00. It is a more realistic model for compound losses or compound gains. 75% loss is twice as bad as 50% loss. 100% loss is infinitely worse. And 100% gain offsets a 50% loss.

**Comment by DidierRLopes** [comment]
Hey guys,

Thank you @Bainsbe for pointing this out!

And thank you @jamesphillipturpin for this solution. I'll label this ticker as a new feature and will work on that flag as well soon. 

Regardless, I think that the right thing to do if the prediction of the stock price is negative, is to output "Invalid prediction" or similar. As realistically, a stock wouldn't go to 0 either.

**Comment by aia** [comment]
Assuming this has been addressed in PR #436
