### ISSUE TITLE
GameStonk Terminal - Elliot Waves literature

### ISSUE THREAD

**Issue by markoreza** [GamestonkTerminal/GamestonkTerminal#464]
Hi,

if you need books on Elliot Wave Theory, go to https://z-lib.org/ and type in "Elliot Wawe"

Thank you!

**Comment by jmaslek** [comment]
Please comment this on #460

**Comment by jmaslek** [comment]
You opened an "issue" for the feature request yesterday.  Any additional information (ie literature) should be commented there and no opened as a new issue.

**Comment by markoreza** [comment]
Sorry, I didn't know.

Can you please make everithing as it should be? And I promise that I won't
do anything else.

Thank you, Marko
