### ISSUE TITLE
Let's talk about modularity.

### ISSUE THREAD

**Issue by exislow** [GamestonkTerminal/GamestonkTerminal#49]
This is a really great job! I like what you did. I like it that much, that I would love to use some of your features in my Game Stonk Telegram Bot (https://github.com/exislow/telegram-stonks-bot).

To do so, it would be great, if you could provide all the features you offer (dd, charts, news etc.) as a separate lib, which can be installed using pip (PyPi). 

I mean, it would be great if the "terminal" feature of your script is just a wrapper for all your libraries. So, everybody could re-use your libraries easily instead of ripping your code apart without almost any chance to get code update.

Also versioning would be great, or at least a stable branch called "release".

**Comment by DidierRLopes** [comment]
Hey @exislow,

I like this idea. I'm fixing the requirements.txt and overall installation process. Once that's out of the way, I can have a further look at this.

**Comment by WP-LKL** [comment]
Great job with GamestonkTerminal @DidierRLopes. I as @exislow would appreciate the ability to integrate components of this project to our own (like `sentiment`) but then handling plotting on client-side and optimizing with `asyncio`  to downstream.

**Comment by DidierRLopes** [comment]
We're working towards achieving this. We still have to define a convention, but it's gradually improving. See https://github.com/DidierRLopes/GamestonkTerminal/pull/216

**Comment by aia** [comment]
The code has been refactored significantly.
