### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by barrel24** [GamestonkTerminal/GamestonkTerminal#490]
latest update.

Under ta - summary returns NaN result

**Comment by jmaslek** [comment]
Can you provide more info?  I just ran it with the latest branch and it works fine.

**Comment by barrel24** [comment]
Strange it may just be my terminal I will reinstall it and try again.

thanks

Christopher Emsley

**Comment by jmaslek** [comment]
If it happens, let me know the ticker and maybe a screenshot.

**Comment by barrel24** [comment]
@jmaslek just cone a complete reinstall
 Welcome to Gamestonk Terminal Ape.

What do you want to do?
   help        help to see this menu again
   update      update terminal from remote
   reset       reset terminal and reload configs
   quit        to abandon the program

   clear       clear a specific stock ticker from analysis
   load        load a specific stock ticker for analysis
   quote       view the current price for a specific stock ticker
   candle      view a candle chart for a specific stock ticker
   view        view and load a specific stock ticker for technical analysis

Stock: ?
Market CLOSED.

   > disc        discover trending stocks,       e.g. map, sectors, high short interest
   > scr         screener stocks,                e.g. overview/performance, using preset filters
   > mill        papermill menu,                 menu to generate notebook reports
   > econ        economic data,                  e.g.: FRED, events
   > pa          portfolio analysis,             supports: robinhood, alpaca, ally
   > crypto      cryptocurrencies,               from: coingecko, coinmarketcap, binance
   > po          portfolio optimization,         optimal portfolio weights from pyportfolioopt
   > gov         government menu,                congress, senate, house trading
   > etf         etf menu,                       from: StockAnalysis.com
   > fx          forex menu,                     forex support through Oanda
   > rc          resource collection,            e.g. hf letters

(✨)> ta
Please load a ticker using <load TICKER>

(✨)> load -t GME -s 2021-01-05
Loading Daily GME stock with starting period 2021-01-05 for analysis.

(✨)> ta

Daily Stock: GME (from 2021-01-05)

Technical Analysis:
   help        show this technical analysis menu again
   q           quit this menu, and shows back to main menu
   quit        quit to abandon program

   view        view historical data and trendlines [Finviz]
   summary     technical summary report [FinBrain API]
   recom       recommendation based on Technical Indicators [Tradingview API]
   pr          pattern recognition [Finnhub]

overlap:
   ema         exponential moving average
   sma         simple moving average
   vwap        volume weighted average price
momentum:
   cci         commodity channel index
   macd        moving average convergence/divergence
   rsi         relative strength index
   stoch       stochastic oscillator
trend:
   adx         average directional movement index
   aroon       aroon indicator
volatility:
   bbands      bollinger bands
volume:
   ad          chaikin accumulation/distribution line values
   obv         on balance volume

(✨) (ta)> summary
NaN

(✨) (ta)>

**Comment by barrel24** [comment]
![gs](https://user-images.githubusercontent.com/84925320/121091578-1e4f9380-c7e2-11eb-933e-2b5a73003530.JPG)

**Comment by jmaslek** [comment]
I have a hypothesis that the command only works during market hours.  Let me confirm that later.

**Comment by barrel24** [comment]
I did try it earlier when market was open and it didn’t work but this was before the reinstall. On discord it was mentioned about the api so will make sure it’s installed properly and I have got a key if I need it although it’s strange it worked without an api before unless finbrain changed something their end. Thanks for your help

**Comment by jmaslek** [comment]
If you go to the api, the response is

`{"ticker":"GME","name":"Gamestop Corporation","technicalSummary":"NaN"}`

**Comment by jmaslek** [comment]
Closing since this is the actual API response.

**Comment by barrel24** [comment]
So confirmed it’s on finbrain end. Thanks for testing.
