### ISSUE TITLE
[FR] Portfolio Analysis based on csv holdings  + XRay 

### ISSUE THREAD

**Issue by universvm** [GamestonkTerminal/GamestonkTerminal#497]
**What's the problem of not having this feature?**
At the moment the only way to analyse positions is using a supported broker. It is currently impossible to visualise holdings not on these brokers meaning I have to rely on other software to keep track of my portfolio. 

Additionally little is done with the portfolio, while a potential nice feature could be the introduction of X-ray like the one morning star provides https://www.morningstar.com/instant-x-ray though it's barely functional and very laggy. 

**Describe the solution you would like**
Ideally a way to load holdings from a csv file or the ability to manually add holdings to a portfolio. 

The X-ray I think would be a nice feature to visualise all your holdings at once 

**Describe alternatives you've considered**
Simply google finance worksheets.

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by jmaslek** [comment]
I like this idea.  Using CSVs should take me no time.

The Xray doesn't seem like would be able to implement it (at least through Morningstar), since the free version requires you to input all your stocks and information.  A report like this would be an amazing feature, but would likely need some community input.

**Comment by universvm** [comment]
That's great about the CSV. 

About the X-Ray feature, I believe something could be done with TradingView. I don't know if they provide an API but for example here:

https://uk.tradingview.com/markets/stocks-usa/sectorandindustry-sector/electronic-technology/

They have all the companies by the electronic technology sector. 

But as you say more detailed performance would probably have to be defined manually (eg. Small cap, medium cap, growth stock, value stock) etc.

I think there might be an additional complication in the case of ETFs, but ultimately I think that a tool with these metrics would be a super useful feature.

**Comment by jmaslek** [comment]
I added a simple version of the csv ability and a simple groupby command.  The idea is that you can input your data with whatever metric you want (you could specify MidCap vs HighCap or Growth Value, etc) then the basic command will show your value based on whatever grouping you want (column header).

I went ahead and added sector to the data by default, but in the future I can envision more metrics being incorporated by default (even an 'add' command where I could do `add apple -shares 5`.

Let me know your feedback once this is updated then I can start making it more functional (or if you have specific ideas to add, feel free to add them!)

**Comment by universvm** [comment]
@jmaslek within 4 days you've implemented a feature. Man you're amazing, thank you so much. 

I will give it a try over the weekend and let you know asap
