### ISSUE TITLE
Stockgrid.io data is superior data source, specifically for dark pool data streams. 

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#503]
**What's the feature that should be improved?**
Stockgrid.io data is superior for dark pool data streams and potentially a replacement for all Yahoo data sources. 

**Describe how you would like the feature improved**
Searchable by ticker and recall data by specified date window.

**Possibly describe the ideal way to improve this**
Integrate stockgrid.io data points to DD menu after loading ticker for analysis. 

**Additional information**
add, ticker/date specified window, specific query to 'darkpool' command - FINRA data.

**Comment by jmaslek** [comment]
Can you specify more what you are looking for?

Stockgrid does not provide an API for their data with resolution options or OHLC data, so it will not be a replacement for yahoo finance (alpha vantage is also implemented with a key).

There is a DD command implementing stock grid (see #496 ).  The darkpool command is specifically designed to fetch FINRA data.

**Comment by deeleeramone** [comment]
I have been talking with head ape on discord, so I think this nullifies my request. However, I can the FINRA data pulled from darkpool command be queried based on ticker, or other variables?
