### ISSUE TITLE
Options pricing and greek variable data

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#504]
**What's the problem of not having this feature?**
The option chain is an important part of the complete picture: pricing, volume, open interest, strike prices, greek variables. 

**Describe the solution you would like**
Simple text outputs searchable by ticker, potentially option market symbol, with puts/calls ability to select the week/month of the option chain. 

**Describe alternatives you've considered**

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by jmaslek** [comment]
There's a whole option menu with chains and Greeks etc.

Load your ticker then use 'op'

**Comment by deeleeramone** [comment]
Awesome. This did not work for me until I received your email. I updated a bunch of my terminal pip’s and this must have been the source of my confusion. Apologies. Strong work. The public is forever indebted to the creators of this project for bringing knowledge to the people.
