### ISSUE TITLE
Poetry install error

### ISSUE THREAD

**Issue by Pranav4399** [GamestonkTerminal/GamestonkTerminal#513]
https://github.com/GamestonkTerminal/GamestonkTerminal/issues/181#issue-832140715. I'm facing this same issue. Can someone help me resolve this ?

**Comment by DidierRLopes** [comment]
Did you try to do with "pip install" ?

**Comment by aia** [comment]
If Poetry gives you problems (which happens on Windows) go with the 

```
pip install -r requirements.txt
```

https://github.com/GamestonkTerminal/GamestonkTerminal/pull/523
