### ISSUE TITLE
Homepage's "Install" button points to wrong repository

### ISSUE THREAD

**Issue by szabi** [GamestonkTerminal/GamestonkTerminal#515]
The Homepage's (https://gamestonkterminal.vercel.app/)

"Installation guide" and
"become a contributor"

buttons still point to the old repository, https://github.com/DidierRLopes/GamestonkTerminal

Maybe also other links in the homepage. EDIT: yeah, it also affects all the menu items.

**Comment by 7ranceaddic7** [comment]
Add the GitHub link in the upper-right.

**Comment by DidierRLopes** [comment]
@jose-donato has made the repo available here https://github.com/GamestonkTerminal/landing-page so from now onwards everyone will also be able to improve the code of the browser!

@jose-donato I can close this ticket right?

**Comment by DidierRLopes** [comment]
This has been fixed now :)
