### ISSUE TITLE
Get a python error when viewing "warnings" for some companies

### ISSUE THREAD

**Issue by darthsahab** [GamestonkTerminal/GamestonkTerminal#517]
Tried JPM and CB. Both fail. I am sure , based on the error there may be more.

> > load -t JPM
> Loading Daily JPM stock with starting period 2019-01-02 for analysis.
> 
> > dd
> 
> Daily Stock: JPM (from 2019-01-02)
> 
> Due Diligence:
>    help          show this fundamental analysis menu again
>    q             quit this menu, and shows back to main menu
>    quit          quit to abandon program
> 
>    news          latest news of the company [News API]
>    red           gets due diligence from another user's post [Reddit]
>    analyst       analyst prices and ratings of the company [Finviz]
>    rating        rating of the company from strong sell to strong buy [FMP]
>    pt            price targets over time [Business Insider]
>    rot           rating over timefrom strong sell to strong buy [Finnhub]
>    est           quarter and year analysts earnings estimates [Business Insider]
>    ins           insider activity over time [Business Insider]
>    insider       insider trading of the company [Finviz]
>    sec           SEC filings [Market Watch]
>    short         short interest [Quandl]
>    warnings      company warnings according to Sean Seah book [Market Watch]
>    dp            dark pools (ATS) vs OTC data [FINRA]
>    ftd           fails-to-deliver data [SEC]
>    shortview     price vs short interest volume [Stockgrid.io]
>    darkpos       net short vs position [Stockgrid.io]
> 
> (dd)> warnings
> **"Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['Interest Expense', 'EBITDA'], dtype='object', name='Item'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"**

**Comment by DidierRLopes** [comment]
This is because the source doesn't contain EBITDA.

Check: https://www.marketwatch.com/investing/stock/JPM/financials/income

**Comment by DidierRLopes** [comment]
#519 outputs a nice warning for this. The reason for it is that MarketWatch doesn't contain the financial row necessary to check the warnings.
