### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by 3dhistory** [GamestonkTerminal/GamestonkTerminal#522]
Hello,
I am toying around with the terminal but get above error followed by "ImportError: numpy.core.multiarray failed to import" on start using numpy 1.19.5. With numpy 1.21.1 installed via "pip install numpy -I" the terminal opens with some numpy .dll warnings but seems to work OK. 

However, tensorflow 2.5 doesn't like numpy 1.21.1 or 1.20.2 as suggested in the troubleshoot page.  PRED  ends up with this error message: "Cannot convert a symbolic Tensor (lstm/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported".

What do I do wrong? 
Thomas

**Comment by 3dhistory** [comment]
I forgot. I am using Python 3.9.5 and Gamestonk in a virualenv.

**Comment by aia** [comment]
Try following the same steps for the setup that we have in the continuous integration - https://github.com/GamestonkTerminal/GamestonkTerminal/runs/2924700399?check_suite_focus=true

**Comment by CoconutMacaroon** [comment]
Not a full solution, but I fixed this by running `pip install --upgrade numpy`. It complained a bit about dependency conflicts, but that fixed the issue for me.

**Comment by DidierRLopes** [comment]
Assuming this has been fixed by now, hence closing this ticket
