### ISSUE TITLE
Make installation more user-friendly

### ISSUE THREAD

**Issue by sbstn87** [GamestonkTerminal/GamestonkTerminal#524]
Hi,

is it possible to make the installation process more user-friendly? Like creating a traditional Windows installer or an executable with the pyinstaller library? Maybe a fllatpak release for Linux?

**Comment by DidierRLopes** [comment]
This is definitely our priority number 1. This would make our user base to grow quite substantially, as this is still a bottleneck for multiple users.

**Comment by DidierRLopes** [comment]
Closing this ticket because docker installation makes everything extremely smooth.
