### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bam607** [GamestonkTerminal/GamestonkTerminal#527]
`(gst) C:\Users\Bam60\GamestonkTerminal>
(gst) C:\Users\Bam60\GamestonkTerminal>python terminal.py
Traceback (most recent call last):
  File "C:\Users\Bam60\anaconda3\envs\gst\lib\site-packages\git\__init__.py", line 87, in <module>
    refresh()
  File "C:\Users\Bam60\anaconda3\envs\gst\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "C:\Users\Bam60\anaconda3\envs\gst\lib\site-packages\git\cmd.py", line 306, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "terminal.py", line 16, in <module>
    from gamestonk_terminal.main_helper import (
  File "C:\Users\Bam60\GamestonkTerminal\gamestonk_terminal\main_helper.py", line 20, in <module>
    import git
  File "C:\Users\Bam60\anaconda3\envs\gst\lib\site-packages\git\__init__.py", line 89, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

(gst) C:\Users\Bam60\GamestonkTerminal>`

**Comment by bam607** [comment]
Not sure how to get past this problem. I'm also a python Noob.

**Comment by DidierRLopes** [comment]
> Not sure how to get past this problem. I'm also a python Noob.

I'm gonna remove git dependence, more users are having this issue and the reason is still unknown. I'll let you know in here when it should not fail anymore.

In the meantime, if you want to still be able to install the terminal you can do the following:

Edit the file `gamestonk_terminal/main_helper.py` by removing this line `import git` and also removing this 
```
    # Print first welcome message and help
    print(
        f"\nWelcome to Gamestonk Terminal Beta ({str(git.Repo('.').head.commit)[:7]})"
    )
```

Join our discord if you need help, people are always keen to help in there :)

**Comment by bam607** [comment]
> > Not sure how to get past this problem. I'm also a python Noob.
> 
> I'm gonna remove git dependence, more users are having this issue and the reason is still unknown. I'll let you know in here when it should not fail anymore.
> 
> In the meantime, if you want to still be able to install the terminal you can do the following:
> 
> Edit the file `gamestonk_terminal/main_helper.py` by removing this line `import git` and also removing this
> 
> ```
>     # Print first welcome message and help
>     print(
>         f"\nWelcome to Gamestonk Terminal Beta ({str(git.Repo('.').head.commit)[:7]})"
>     )
> ```
> 
> Join our discord if you need help, people are always keen to help in there :)

That seemed to do the trick! Thank you! And I've joined the Discord, I'll keep in touch!

**Comment by DidierRLopes** [comment]
#526 should fix this now. It basically does what I asked you to do here. Hence, closing this ticket.

**Comment by CaptainTollBooth** [comment]
First time attempting to run the terminal.py and I get this error.

However, when I try and locate gamestonk_terminal/main_helper.py, I don't even see that file.

I see this issue was closed.  But could there be an alternative workaround?
