### ISSUE TITLE
[IMPROVE] Publish dockerfile

### ISSUE THREAD

**Issue by chaychoong** [GamestonkTerminal/GamestonkTerminal#571]
It will be sweet to be able to run this by simply (if one has docker) typing

```bash
docker run --rm -it -v .env:/app/.env ghcr.io/GamestonkTerminal/GamestonkTerminal
```

To do this, we'll need to

- [ ] Agree on a release flow (can just do it by tagging branches to start off with)
- [ ] Create a github actions workflow to build and publish the docker image to github's container registry
- [ ] Modify README with the relevant instructions
- [ ] Publish the first release

**Comment by DidierRLopes** [comment]
@aia is working on this. Feel free to contribute!
