### ISSUE TITLE
oanda practice account - Insufficient authorization to perform request

### ISSUE THREAD

**Issue by devwolff** [GamestonkTerminal/GamestonkTerminal#650]
I'm using an practice account. So I changed environment from "live" -> "practice". I also got "Insufficient authorization to perform request". 
 
Just double checking.. So the code on oanda only work with "live" account?

I tried below with my practice account

```
curl -H "Authorization: Bearer 12345678900987654321-abc34135acde13f13530" https://api-fxpractice.oanda.com/v3/accounts/{account_ID}/summary
```

and it works fine.

_Originally posted by @devwolff in https://github.com/GamestonkTerminal/GamestonkTerminal/issues/417#issuecomment-894735632_

**Comment by DidierRLopes** [comment]
I just created an account to test the Oanda menu a long time ago, and it has since expired the free trial.

Could you add a flag on `config_terminal.py` like:
```
# OANDA_ACCOUNT_TYPE between "live" and "practice"
OANDA_ACCOUNT_TYPE = os.getenv("GT_OANDA_ACCOUNT_TYPE") or "REPLACE_ME"
OANDA_ACCOUNT = os.getenv("GT_OANDA_ACCOUNT") or "REPLACE_ME"
OANDA_TOKEN = os.getenv("GT_OANDA_TOKEN") or "REPLACE_ME"
``` 

And then 
`client = API(access_token=cfg.OANDA_TOKEN, environment=cfg. OANDA_ACCOUNT_TYPE)` or something like that?

Or would you rather me fixing it?

**Comment by devwolff** [comment]
Yeh, I will give it a go. Thanks! You guys ve been doing some great work btw. Keep it up!!

**Comment by DidierRLopes** [comment]
> Yeh, I will give it a go. Thanks! You guys ve been doing some great work btw. Keep it up!!

Thanks for the help, and for the feedback! This is just the beginning!

Feel free to join our discord and ping me if you need help around this. Otherwise I can work on it myself :)

**Comment by devwolff** [comment]
It works now

**Comment by DidierRLopes** [comment]
For future reference, @devwolff worked on a fix. Check #654 !
