### ISSUE TITLE
Can't start terminal.py with a error called "list index out of range"

### ISSUE THREAD

**Issue by yingjiaoyu** [GamestonkTerminal/GamestonkTerminal#680]
**Describe the bug**

When I try to start terminal.py, the result alway these below:

> **Traceback (most recent call last):
>   File "terminal.py", line 56, in <module>
>     from gamestonk_terminal.etf import etf_controller
>   File "C:\Users\yuyingjiao\GamestonkTerminal\gamestonk_terminal\etf\etf_controller.py", line 12, in <module>
>     from gamestonk_terminal.etf.stockanalysis_model import (
>   File "C:\Users\yuyingjiao\GamestonkTerminal\gamestonk_terminal\etf\stockanalysis_model.py", line 18, in <module>
>     all_links = soup[0].findAll("li")
> IndexError: list index out of range**

**Comment by DidierRLopes** [comment]
Hey @yingjiaoyu ,

This has been solved since. Could you do a `git pull` to get latest version of the terminal?
