### ISSUE TITLE
[FR] Up/down arrow to cycle through recent commands

### ISSUE THREAD

**Issue by soundchippy** [GamestonkTerminal/GamestonkTerminal#693]
Please could you include ability to cycle through command history by pressing up/down arrows as per other terminal prompts.

This would improve my workflow in various areas - correcting incorrectly typed strings, loading different time stamps quickly etc.

Many thanks

**Comment by DidierRLopes** [comment]
> Please could you include ability to cycle through command history by pressing up/down arrows as per other terminal prompts.
> 
> 
> 
> This would improve my workflow in various areas - correcting incorrectly typed strings, loading different time stamps quickly etc.
> 
> 
> 
> Many thanks
> 
> 

Hey @soundchippy ,

This is actually one of our feature flags. We should probably set it True as default, as most of the people like/use this one.

You can check the feature_flags.py file and it's the PROMPT TOOLKIT one. 

Let me know if that works so we can close this ticket :)

**Comment by soundchippy** [comment]
Works like a charm!

Many thanks for the quick reply!

**Comment by DidierRLopes** [comment]
> Works like a charm!
> 
> Many thanks for the quick reply!

No problem at all! Thanks for using our terminal! 

Have an amazing weekend ❤️

**Comment by MLNW** [comment]
> This is actually one of our feature flags. We should probably set it True as default, as most of the people like/use this one.

Yes, this would be a sensible default ..
