### ISSUE TITLE
Pred Module Crashes - No indication of why[Bug]

### ISSUE THREAD

**Issue by jigsawsecurity** [GamestonkTerminal/GamestonkTerminal#719]
**Describe the bug**
When loading a ticker and running pred the following occurs

(✨) (stocks)> pred
479653 Illegal instruction     (core dumped) python3 terminal.py

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior
I am running the latest code and am not sure what is causing this to occur so any ideas on what I could check to potentially fix the issue. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 LTS
 - Python version 3.8.10
 

**Additional context**
Not sure if you have seen this but would love to get this part of the application working correctly but the only error message I see is the illegal instruction when the core dump occurs.

**Comment by jmaslek** [comment]
So just googling that issue shows that it seems to be an issue with tensorflow.  What version are you using ( `pip list | grep tensorflow` ).  You may need to try uninstalling it then reinstalling it

**Comment by jigsawsecurity** [comment]
Reinstalling, I'll let you know if it fixes the issue. 

tensorflow                    2.6.0
tensorflow-estimator          2.6.0

**Comment by jmaslek** [comment]
So I am on tf 2.5.0 personally and I have no issues

**Comment by jigsawsecurity** [comment]
Uninstalled and reinstalled and exact same error. Let me see if 2.5.0 works. Trying to figure out how to fix it also but wanted to let you know I'm also looking into it. If I figure it out i'll update versions and info here.

**Comment by jmaslek** [comment]
I was able to run with tf 2.6.0.

If you open python are you able to "import tensorflow"?  That will tell you if it's a tf issue

The other solution I saw after googling was to just recreate your environment

**Comment by jigsawsecurity** [comment]
So what I run that I'm getting the following, Googling now. 

import-im6.q16: unable to open X server `' @ error/import.c/ImportImageCommand/359.

**Comment by jigsawsecurity** [comment]
Actually had to run in the python interpreter. After doing that I get the following: 

>>> import tensorflow
Illegal instruction (core dumped)

So it's defintely a problem with tensorflow. 

pip show tensorflow
Name: tensorflow
Version: 2.6.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: flatbuffers, clang, google-pasta, wheel, grpcio, gast, keras, protobuf, keras-preprocessing, tensorboard, tensorflow-estimator, numpy, typing-extensions, termcolor, absl-py, h5py, wrapt, opt-einsum, astunparse, six
Required-by:

**Comment by jmaslek** [comment]
So we recently bumped out tf requirement.  If you do a clean install of the environment, do you still run into this tf issue?

**Comment by DidierRLopes** [comment]
Closing this ticket for lack of activity
