### ISSUE TITLE
[Bug] Discord invite link is invalid

### ISSUE THREAD

**Issue by CoconutMacaroon** [GamestonkTerminal/GamestonkTerminal#723]
**Describe the bug**
Both the Discord link in the README and on the website are broken.

**To Reproduce**
1. Navigate to the README or website
2. Click on the Discord link
3. Observe that it is broken

**Screenshots**
![image](https://user-images.githubusercontent.com/45187468/131223263-8cb0c9bc-0d43-4fd8-becd-3382cbb2ab17.png)

**Desktop (please complete the following information):**
> I don't think this info is important here, but the form wants it, so here it is
 - OS: Windows 11, Dev Channel, Build 22000.168, using Windows Subsystem for Linux, which has Ubuntu as the distro.
 - Python version `Python 3.8.10`

**Additional context**
N/A

**Comment by jmaslek** [comment]
So I just tested: https://discord.gg/Up2QGbMKHY

And it directs to joining the server.

**Comment by CoconutMacaroon** [comment]
Thank you. That link worked... but the one on the website doesn't work for me. I attached a screen capture showing the issue.

https://user-images.githubusercontent.com/45187468/131224839-ecd9acb3-8bb7-49df-ae35-f7e51debc8e5.mp4

**Comment by jmaslek** [comment]
@jose-donato

**Comment by jose-donato** [comment]
> @jose-donato

on it

**Comment by CoconutMacaroon** [comment]
> on it
If it would be helpful, I can try to send a PR, but I'm not familiar with where the website source is (or if it is even public), but if it is, I'm happy to send a PR with the updated link. I can also update the `README` if it would be helpful.

**Comment by DidierRLopes** [comment]
> > on it
> 
> 
> 
> If it would be helpful, I can try to send a PR, but I'm not familiar with where the website source is (or if it is even public), but if it is, I'm happy to send a PR with the updated link. I can also update the `README` if it would be helpful.

Hey there. Absolutely!

This is the repository https://github.com/GamestonkTerminal/landing-page feel free to open a PR :)

**Comment by CoconutMacaroon** [comment]
I just cloned the repo and am looking at it, but I'm not sure where to update the link, as I can't find the old link anywhere in the repo. Would you mind pointing me at the file that contains the link...? I don't see it

**Comment by CoconutMacaroon** [comment]
@DidierRLopes

**Comment by DidierRLopes** [comment]
> @DidierRLopes 

Sorry for the time to reply, 

I actually haven't touched in the landing page, this is all @jose-donato expertise.

I could have a look for you but I'm not at home this weekend :/

**Comment by jose-donato** [comment]
> I just cloned the repo and am looking at it, but I'm not sure where to update the link, as I can't find the old link anywhere in the repo. Would you mind pointing me at the file that contains the link...? I don't see it

Hey, we built the website using [Next.js](https://nextjs.org/). If you already cloned please pull the code again because the code that was on the main branch was not the one deployed in https://gamestonkterminal.netlify.app/
Sorry about that.

You can find the link in `pages/index.js` ([link](https://github.com/GamestonkTerminal/landing-page/blob/main/pages/index.js)) and let me know if you need any extra help.

Thanks for pointing this out 🙌
