### ISSUE TITLE
[Bug]Running tsne on a ticker gives "at least one array or dtype is required" error

### ISSUE THREAD

**Issue by sug4ndh** [GamestonkTerminal/GamestonkTerminal#744]
**Describe the bug**
After loading a ticker when tsne is executed to find similar companies, "at least one array or dtype is required" is given as output.

**To Reproduce**
1) load the ticker, ROKU for example 
2) Go inside ca menu
3) run tsne

**Screenshots**
![gmstptrml](https://user-images.githubusercontent.com/2163026/132961214-968bec6a-26d5-4a7b-b433-ffa1157c4318.png)

**Desktop (please complete the following information):**
 - OS: Linuxmint 20.1
 - Python version: 3.8.0

**Additional context**
Used Pyenv to create a virtualenv and requirements-full.txt to install dependencies instead of using conda.

**Comment by jmaslek** [comment]
1) I assume you are on the latest pull?

2) From that menu, if you try loading an sp500 stock (ie 'load aapl' ) does the command work?

**Comment by sug4ndh** [comment]
1) I am using the pull from Sep 9.

2) Yes, it works with Apple.

**Comment by jmaslek** [comment]
So I am not able to recreate the error message.  Is this still happening for you?

**Comment by sug4ndh** [comment]
Yes, I am still having this issue. I can maybe try to pull the latest changes and see if that changes anything.

**Comment by jmaslek** [comment]
I don't think the command has been touched, so updating will likely not change anything.

If you run `poetry update` to make sure dependencies are up to date - does that fix the issue?

I was able to run with ROKU loaded

**Comment by sug4ndh** [comment]
Like you said pulling the latest changes didn't do anything. I installed dependencies using `pip install -r requirements-full.txt` inside virtualenv and therefore, do not have poetry installed :/

**Comment by jmaslek** [comment]
If you look at `pip list|grep scikit` are you on scikit-learn 0.24.2 ?

**Comment by sug4ndh** [comment]
Yes, scikit-learn is version 0.24.2

**Comment by jmaslek** [comment]
Okay so I am not sure what it could be then.  The only difference is I am running on python 3.9.5 (I also am not familiar with LinuxMint)

**Comment by DidierRLopes** [comment]
I just tested this as well, and it's working fine with ROKU :/

**Comment by DidierRLopes** [comment]
Can you help us debug this @sug4ndh ?

In the ca_controller in line 180 can you do these 2 changes:

![image](https://user-images.githubusercontent.com/25267873/133346085-f6308b5e-42aa-431d-bd44-d77cc4ec8b09.png)

This will effectively make the terminal "break" when you do the steps you mentioned above, at which point you'll get a traceback error which will show what's the line giving the problem, and that way we can further investigate.

**Comment by sug4ndh** [comment]
@DidierRLopes, sure. This is the trace that I got:
```
Traceback (most recent call last):
  File "GamestonkTerminal/terminal.py", line 282, in <module>
    terminal()
  File "GamestonkTerminal/terminal.py", line 255, in terminal
    process_input = t_controller.switch(an_input)
  File "GamestonkTerminal/terminal.py", line 122, in switch
    return getattr(
  File "GamestonkTerminal/terminal.py", line 161, in call_stocks
    return stocks_controller.menu()
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/stocks_controller.py", line 502, in menu
    process_input = stocks_controller.switch(an_input)
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/stocks_controller.py", line 174, in switch
    return getattr(
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/stocks_controller.py", line 345, in call_ca
    ret = ca_controller.menu(self.ticker, self.start, self.interval, self.stock)
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/comparison_analysis/ca_controller.py", line 998, in menu
    process_input = ca_controller.switch(an_input)
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/comparison_analysis/ca_controller.py", line 398, in switch
    return getattr(
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/comparison_analysis/ca_controller.py", line 185, in call_tsne
    self.similar = yahoo_finance_model.get_sp500_comps_tsne(
  File "/home/sug/stocks/GamestonkTerminal/gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_model.py", line 108, in get_sp500_comps_tsne
    normalized_movements = normalize(rets)
  File "/home/sug/.pyenv/versions/stock/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/sug/.pyenv/versions/stock/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 1904, in normalize
    X = check_array(X, accept_sparse=sparse_format, copy=copy,
  File "/home/sug/.pyenv/versions/stock/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/sug/.pyenv/versions/stock/lib/python3.8/site-packages/sklearn/utils/validation.py", line 597, in check_array
    dtype_orig = np.result_type(*dtypes_orig)
  File "<__array_function__ internals>", line 5, in result_type
ValueError: at least one array or dtype is required
```

**Comment by jmaslek** [comment]
So my hypothesis is that trying to add the non-sp500 ticker breaks the data frame.  Can you go into the comparison_analysis/yahoo_finance_model.py and add the following prints to see if everything looks okay:

![Screen Shot 2021-09-16 at 9 45 49 AM](https://user-images.githubusercontent.com/18151143/133623796-19820cf1-6310-4a35-99b1-c884b1c69848.png)

**Comment by sug4ndh** [comment]
The shapes of the arrays are as follows:
```
(254, 505)
(254, 506)
(506, 0)
```

**Comment by jmaslek** [comment]
So that is the issue.  `close_vals` is not updating correctly.  No idea why on your machine it doesn't do that:

you can try the following:
```
close_vals = close_vals.insert(loc=0,column = ticker, values = yf.download(ticker, start=close_vals.index[0], progress=False)["Adj Close"].values )
```
But I am still lost as to why that would be needed.

**Comment by sug4ndh** [comment]
After changing the lines, it gives an error "Length of values (255) does not match length of index (254)"

**Comment by jmaslek** [comment]
So it should be `.values[:-2]`  (or .values[:,-1]).  I don't account for "todays" price

**Comment by sug4ndh** [comment]
With `.values[:,-1] `and `.values[:,-2]`, it gives "too many indices for array: array is 1-dimensional, but 2 were indexed"

with `.values[:-2]`, it gives "Length of values (253) does not match length of index (254)"
and with `.values[:-1]`, it gives "'NoneType' object has no attribute 'fillna' "

**Comment by jmaslek** [comment]
So actually, it adds the df column just fine.  Its the rets command that makes the df empty.  If you get rid of the .dropna() in rets, do you get a different error (keep the shape lines in to see if you still get 0 as the second shape).

**Comment by sug4ndh** [comment]
I changed the dropna line to this :
`close_vals.fillna(method="ffill").fillna(method="bfill").pct_change().T`

And this output that I got:
```
(253, 505)
(253, 506)
(506, 253)
Input contains NaN, infinity or a value too large for dtype('float64'). 
```

**Comment by DidierRLopes** [comment]
Do you still have this issue? @sug4ndh

**Comment by sug4ndh** [comment]
@DidierRLopes Yes

**Comment by DidierRLopes** [comment]
I'll fix this now. Give me a couple of minutes to investigate

**Comment by DidierRLopes** [comment]
Should be fixed now @sug4ndh . It was a tricky one. But let me know if it works for you now!

**Comment by sug4ndh** [comment]
Yes, it works now! Thanks! :) @DidierRLopes
