### ISSUE TITLE
[IMPROVE] Shorthand notation inputs for main menu entries

### ISSUE THREAD

**Issue by sug4ndh** [GamestonkTerminal/GamestonkTerminal#746]
**What's the feature that should be improved?**
In the main menu, perhaps, the entries can have a shorthand notation for input? For e.g. instead of entering 'stocks', maybe just 's' should present the stocks menu.

**Describe how you would like the feature improved**
Right now, the users have to input the full word in the main menu like stocks, crypto, etc. Having a shorthand notation like s for stocks, c for crypto would be relatively faster.

**Comment by jmaslek** [comment]
#751 closes this.  Thanks for the input!
