### ISSUE TITLE
[FR] Help Screen

### ISSUE THREAD

**Issue by jigsawsecurity** [GamestonkTerminal/GamestonkTerminal#763]
**What's the problem of not having this feature?**
A clear description of what you are lacking, or why you need this additional feature.

**Describe the solution you would like**
Instead of linking to the help screens it would be awesome if we had a help menu on each menu that would bring up the text inside the console, right now it just provides the link at the top of the screen. 

**Describe alternatives you've considered**
Maybe I’ll do a pull request and help work on it 

**Additional information**
I would think having a help menu on each page would allow you to see all of the documentation in one place so you don’t have to open a browser to see the full text description of the menu items so you can work quicker when changing parameters. Just a suggestion. 

You guys are doing great with this product, I’m finding myself using it more and more on a daily basis.

**Comment by DidierRLopes** [comment]
Hey @jigsawsecurity,

Thanks for the feedback. We absolutely love hearing that you are using it more and more, so feel free to let us know if there's any other particular feature you would like :)

Regarding the help menu, I'm not sure I fully understand the idea. Can you be more explicit on how you would foresee such feature?

Also, have you seen this: https://gamestonkterminal.github.io/GamestonkTerminal/ ? It's 70% from complete as it lacks a lot of example images, but you can get the main commands and their descriptions. We're looking towards dropping the README documentation, as it was a bit "hidden" and doesn't allow a nice search engine as Hugo does.

**Comment by jigsawsecurity** [comment]
I’m aware of the reference pages mentioned. I have to refer to that quite often when the help option doesn’t explain what the various options do. I had to create a cheat sheet. It would be nice if there was descriptions on each of the flags in help. I realize this thing is evolving quickly so adding more context means more time developing. 

I just wanted to drop the idea so you don’t have to refer to a second area to figure out what
Options (I didn’t do that on purpose) exist! 

Feel free to close, just wanted to make that suggestion. Also the tensor flow issue I previously ran into was because the CPU didn’t support a required instruction. Moving my install to a newer processor fixed that issue. 

Any questions let me know.

**Comment by DidierRLopes** [comment]
So if I understand correctly, isn't using "-h" what you are looking for?

Like "load -h"?

Nice that the new processor fixed the tensorflow issue :)

**Comment by jigsawsecurity** [comment]
Im gonna close this. I did have another question. 

Can you explain how the predictive models work? I’m looking at some examples I have found in tensorflow and using sequence data from
The S&P and previous stock prices to predict movement in the future. I guess I’m trying to understand each of the predictive flows that have been implemented.
