### ISSUE TITLE
[FR] Add ticker lookups to Arkord command

### ISSUE THREAD

**Issue by emcquaid** [GamestonkTerminal/GamestonkTerminal#779]
**What's the problem of not having this feature?**
Seems like it would be very easy to implement this feature as Arkord command already exists.  

**Describe the solution you would like**
Cathie's Ark is a powerful site that allows us to see all activity of ARK funds.  You can also see historical activity on each {ticker} by visiting https://cathiesark.com/ark-combined-holdings-of-{ticker}

for example:
https://cathiesark.com/ark-combined-holdings-of-pltr

**Describe alternatives you've considered**
You can go straight to 
https://cathiesark.com/ark-combined-holdings-of-
and add your ticker.

**Additional information**
but this is why we love gst, never need to leave the terminal.

thanks y'all.

**Comment by jmaslek** [comment]
#784   Thanks for the suggestion!

**Comment by emcquaid** [comment]
`(stocks)>(dd)> arktrades`

responded with 
`'trades'`


when I used 
`(stocks)>(dd)> arktrades -n 25`

it produced the report.

Suggestion is to default to -n 10 so the report will be generated on 
`(stocks)>(dd)> arktrades`

**Comment by emcquaid** [comment]
Also, report should include column for ticker, imo, so if shared, there is no explanation needed.

**Comment by jmaslek** [comment]
What ticker?  And what do you mean by report?  Nothing should be different between -n 10  and  -n 25 as they both just take df.head().  The 'trades' is the json response, so that would likely mean something is wrong with the request.
