### ISSUE TITLE
Comprehensive historical daily volume and price statistics [FR]

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#817]
Volume is probably the single most important metric along with daily price open/close/high/low. There currently is no method for retrieving the historical daily data.

**Comment by jmaslek** [comment]
So is there anything specific you would like to see?

If you go to `qa` and do `pick Volume` you can do some basic quantitative analysis on volume.

**Comment by deeleeramone** [comment]
Raw data. Not a chart not quantitative analysis. Basic raw data. Displayed tables with daily historical values for Volume and open/close/high/low/change since previous day price data. Something like this:

https://chartexchange.com/symbol/nasdaq-hut/historical/ <https://chartexchange.com/symbol/nasdaq-hut/historical/>

There should be a way to filter by date range and sort volume and change in price columns ascending or descending.

**Comment by deeleeramone** [comment]
The same can be applied to individual options like this:

https://chartexchange.com/symbol/opra-hut20211015c2.5/historical/ <https://chartexchange.com/symbol/opra-hut20211015c2.5/historical/>

**Comment by colin99d** [comment]
I can work on this tonight

**Comment by colin99d** [comment]
That feature is not currently available.

**Comment by deeleeramone** [comment]
This is why I am requesting it.

**Comment by DidierRLopes** [comment]
![Screenshot 2022-01-20 at 13 46 40](https://user-images.githubusercontent.com/25267873/150350649-fb168847-5491-4018-863b-5c995946bb5c.png)

I believe this addresses this issue! Will close this!
