### ISSUE TITLE
[Bug] test_fa_yield_curve_model test is stalling after 3+ hours

### ISSUE THREAD

**Issue by aia** [GamestonkTerminal/GamestonkTerminal#825]
![image](https://user-images.githubusercontent.com/535247/137780171-a351861d-376a-42b6-9316-9edd9a5c2d25.png)

**Comment by DidierRLopes** [comment]
![Screenshot 2022-01-20 at 13 44 44](https://user-images.githubusercontent.com/25267873/150350304-8e17f14b-ab6a-45e3-953f-ce72b23712bd.png)

No longer stalling. Closing this PR.
