### ISSUE TITLE
[FR] Generate a report for above average volumes for calls and puts? Preferably a list of stocks. 

### ISSUE THREAD

**Issue by CB30** [GamestonkTerminal/GamestonkTerminal#850]
**What's the problem of not having this feature?**
A clear description of what you are lacking, or why you need this additional feature.**

Analysis of multiple stock volumes made much simpler. Compared to pulling each stock volume manually.  

****Describe the solution you would like****

**A description of what you think would be the best solution for this. From user inputs, to an output.**

User input could be AAV(Above Average Volumes) or BAV(Below Average Volumes). An output could have a spreadsheet of a list stocks with average volume and the dates where volume was above the average. A customizable date range would be cool too.

For example, if average stock volume is 1,000,000 and it jumps to 1,200,000, it would be added to the list of AAVs. 

****Describe alternatives you've considered****
Manual Analysis. Pretty Slow

****Additional information****

Maybe an ability to load multiple stocks at the same time via "load" command. 

![Screen Shot 2021-10-23 at 9 22 07 PM](https://user-images.githubusercontent.com/84421660/138576257-faa640de-1d82-4a1c-8715-3ce6aba00a81.png)

**Comment by DidierRLopes** [comment]
Although we don't directly do this, there's a way you can do it through our `stocks/scr` menu. 

See below:
<img width="1550" alt="Screenshot 2022-01-20 at 13 39 57" src="https://user-images.githubusercontent.com/25267873/150349560-fbf9b558-187a-48a5-a7f6-9b08992fc675.png">

```
Relative Volume
Ratio between current volume and 3-month average value, intraday adjusted.

Relative Volume = Current Volume / 3-month Average Volume
```

This is how you can create your own presets:
https://github.com/GamestonkTerminal/GamestonkTerminal/tree/main/gamestonk_terminal/stocks/screener/presets

For options as @jmaslek said we have `unusual activity`.

Owing to this I will close this PR. If you are not happy with this resolution feel free to re-open this PR.
