### ISSUE TITLE
API Key test [IMPROVE]

### ISSUE THREAD

**Issue by nikisix** [GamestonkTerminal/GamestonkTerminal#88]
Would be nice if `tests/conftest.py` tested the api connection creds by making trivial requests to each service.

**Comment by mjt91** [comment]
The tests should not test if an API is working. What if the API itself is not reachable? This would lead to failing tests. An optimal test in my opinion would be testing if API keys are present all together. Also mocking the request responses.

**Comment by nikisix** [comment]
Probably both the unit and integration test (foreign api) would be appropriate; the former being quicker to implement but less useful (a user knows when they've entered a key).

https://www.guru99.com/unit-test-vs-integration-test.html

**Comment by DidierRLopes** [comment]
I'm still learning about unit tests. And with the fast-paced of the terminal + full-time job, it's hard to find time to get  around it.

If you feel like this is needed, and have knowledge in this area. Feel free to do a PR against it, and we'll review it :)

We're prioritising features at the moment, but at some point we need to developer proper automation to make sure that regressions aren't introduced.

**Comment by jmaslek** [comment]
#556 this addressed the original idea of making trivial requests to defined API keys (not mocking the requests as a purest_
