### ISSUE TITLE
[Bug] (stocks)>(fa)>key: Passing list-likes to .loc or [] with any missing labels is no longer supported. 

### ISSUE THREAD

**Issue by deeleeramone** [GamestonkTerminal/GamestonkTerminal#939]
![Screen Shot 2021-11-11 at 6 35 45 PM](https://user-images.githubusercontent.com/85772166/141399406-3ddbc71c-eea4-4505-a99b-52702fe8ef7a.png)

(✨) (stocks)>(fa)> key
"Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['Payout ratio'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

**Comment by jmaslek** [comment]
Closing via #954
