### ISSUE TITLE
[Bug]Float Errors in stocks/gov/

### ISSUE THREAD

**Issue by grahuloverthere** [GamestonkTerminal/GamestonkTerminal#948]
**Describe the bug**
When running "topbuys" from the stocks/gov menu, I always get an error saying "could not convert string to float: '>$5000000' "

**To Reproduce**
python terminal.py
stocks
gov
topbuys

**Screenshots**
<img width="1118" alt="Screen Shot 2021-11-15 at 12 40 33" src="https://user-images.githubusercontent.com/75821256/141828896-6f13cbd0-84d1-478d-923e-ae20eef198f4.png">

**Desktop (please complete the following information):**
- OS: Mac Monterey with Intel Core i7. Also reproducible on a Mac Monterey with M1.
- Python version 3.8.8

**Additional context**
This command used to work well in previous releases. I don't make any local code changes to GamestonkTerminal. I just update from the repository every couple of weeks using the "git pull" command.

**Comment by jmaslek** [comment]
Thanks!  Looks like a stock purchase (sell) was >$5000000 and we did not have any logic to convert that to a "range", so I added that in and should work once we update it :)
