### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 23errg** [GamestonkTerminal/GamestonkTerminal#987]
**Describe the bug**
Pressing ?/q to go back to previous menu results  in error and force quit.

**To Reproduce**
Pressing ?/q to go back to previous menu .

<img width="669" alt="2021-11-26 (8)" src="https://user-images.githubusercontent.com/74156936/143572909-0daeab1f-5e1a-4639-89a3-3729b3dcc6cb.png">

**Desktop (please complete the following information):**

- OS: [Windows 11]
- Python version [e.g. 3.9.0]

**Additional context**

Maybe using the command "back" for only go back to previous step would be better then calling  main menu with ?/q.

**Comment by 23errg** [comment]
> Thanks for pointing this out, have already done a fix for it!
> 
> I actually started some work 1 month ago towards having:
> 
>     * q/quit for leaving terminal
> 
>     * b/back for going one menu up
> 
>     * r/reset for doing reset (more for devs or in case you updated a screener or API keys)
> 
> 
> But found that I was quitting the terminal a lot of times by accident because of being so used to the "q", hence why I froze those efforts. Do you think this would improve user experience?

I believe that would improve the user experience.

**Comment by DidierRLopes** [comment]
> > Thanks for pointing this out, have already done a fix for it!
> > I actually started some work 1 month ago towards having:
> > ```
> > * q/quit for leaving terminal
> > 
> > * b/back for going one menu up
> > 
> > * r/reset for doing reset (more for devs or in case you updated a screener or API keys)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But found that I was quitting the terminal a lot of times by accident because of being so used to the "q", hence why I froze those efforts. Do you think this would improve user experience?
> 
> I believe that would improve the user experience.

Thanks for feedback.

Issue should be fixed now!
